server:
   port:80

# jsp 集成配置  不要使用tab键输入空格
spring:
   mvc:
     view:
       prefix: WEB-INF/jsp/
       suffix: .jsp
   
   
   datasource:
     url: jdbc:mysql://localhost:3306/c71-s3-pnjh-blog
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
   #配置静态资源路径  
   resources:
      staticLocations: file:/d:/blogimg
   mail:
     # //邮箱服务器地址
     host: smtp.qq.com
     # //用户名
     username: 670743258@qq.com
     # //密码
     password: ljtqhrzzavogbcgi
     default-encoding: UTF-8
     
# // 以谁来发送邮件  用户自定义的参数
mail:
  fromMail: 
    addr: 670743258@qq.com
     
logging:
  level:
    com:
      yc: debug

# log 日志等级：   debug error warn info   
# log.debug("调试信息")  =》 system.out